import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Smart Valve Management',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFF1261A0))),home:const Login());}
class Login extends StatelessWidget{const Login({super.key});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(20),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Card(child:Padding(padding:const EdgeInsets.all(22),child:Column(children:[const Icon(Icons.water_drop,size:72,color:Colors.blue),const SizedBox(height:8),const Text('Smart Valve Management',style:TextStyle(fontSize:27,fontWeight:FontWeight.bold)),const Text('Monitor  •  Control  •  Manage'),const SizedBox(height:24),const Text('Login',style:TextStyle(fontSize:30,fontWeight:FontWeight.bold)),const Text('Agent / Operator'),const SizedBox(height:18),TextField(obscureText:true,decoration:InputDecoration(labelText:'Password',border:OutlineInputBorder(),prefixIcon:Icon(Icons.lock))),const SizedBox(height:6),Align(alignment:Alignment.centerRight,child:TextButton(onPressed:(){},child:const Text('Forgot Password?'))),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const Home())),child:const Padding(padding:EdgeInsets.all(14),child:Text('LOGIN')))),const SizedBox(height:14),const Info('Authentication will be sent to your registered mobile number.'),const SizedBox(height:8),const Info('If app mobile number changes / phone changes, re-authentication is required.')]))))))));}
class Info extends StatelessWidget{final String text;const Info(this.text,{super.key});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.blue.shade50,borderRadius:BorderRadius.circular(10)),child:Text(text));}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{int tab=0;int? zone,ward;void nav(int i)=>setState(()=>tab=i);void add(String what){showDialog(context:context,builder:(_)=>AlertDialog(title:Text('Add $what'),content:TextField(keyboardType:TextInputType.number,decoration:InputDecoration(labelText:'$what No',border:const OutlineInputBorder())),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('CANCEL')),FilledButton(onPressed:()=>Navigator.pop(context),child:const Text('ADD'))]));}
@override Widget build(BuildContext c){final pages=[const Gsm(),const Lora(),const MapPage()];if(tab>0)return Shell(index:tab,child:pages[tab-1]);return Scaffold(appBar:AppBar(title:const Text('Smart Valve Management')),body:SingleChildScrollView(padding:const EdgeInsets.all(16),child:Card(child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Select Zone and Ward',textAlign:TextAlign.center,style:TextStyle(fontSize:26,fontWeight:FontWeight.bold)),const SizedBox(height:18),DropdownButtonFormField<int>(value:zone,decoration:const InputDecoration(labelText:'Zone No',border:OutlineInputBorder()),items:[1,2,3,4,5].map((x)=>DropdownMenuItem(value:x,child:Text('Zone $x'))).toList(),onChanged:(x)=>setState(()=>zone=x)),const SizedBox(height:7),OutlinedButton.icon(onPressed:()=>add('Zone'),icon:const Icon(Icons.add),label:const Text('ADD ZONE')),const SizedBox(height:12),DropdownButtonFormField<int>(value:ward,decoration:const InputDecoration(labelText:'Ward No',border:OutlineInputBorder()),items:[1,2,3,4,5,6,7,8].map((x)=>DropdownMenuItem(value:x,child:Text('Ward $x'))).toList(),onChanged:(x)=>setState(()=>ward=x)),const SizedBox(height:7),OutlinedButton.icon(onPressed:()=>add('Ward'),icon:const Icon(Icons.add),label:const Text('ADD WARD')),const SizedBox(height:20),Row(children:[Expanded(child:Btn('GSM / LTE\nValve View',Icons.cell_tower,()=>nav(1))),const SizedBox(width:12),Expanded(child:Btn('LoRa\nValve View',Icons.cell_tower,()=>nav(2)))]),const SizedBox(height:12),Btn('MAP View',Icons.map,()=>nav(3))])))),bottomNavigationBar:Nav(index:0,onTap:nav));}}
class Btn extends StatelessWidget{final String t;final IconData icon;final VoidCallback onTap;const Btn(this.t,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>FilledButton.icon(onPressed:onTap,icon:Icon(icon),label:Text(t,textAlign:TextAlign.center),style:FilledButton.styleFrom(padding:const EdgeInsets.all(18)));}
class Shell extends StatelessWidget{final Widget child;final int index;const Shell({super.key,required this.child,required this.index});@override Widget build(BuildContext c)=>Scaffold(body:child,bottomNavigationBar:Nav(index:index,onTap:(i){if(i==0)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const Home()));else if(i==1)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const Gsm()));else if(i==2)Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const Lora()));else Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const MapPage()));}));}
class Nav extends StatelessWidget{final int index;final ValueChanged<int> onTap;const Nav({super.key,required this.index,required this.onTap});@override Widget build(BuildContext c)=>NavigationBar(selectedIndex:index,onDestinationSelected:onTap,destinations:const[NavigationDestination(icon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.cell_tower),label:'GSM'),NavigationDestination(icon:Icon(Icons.cell_tower),label:'LoRa'),NavigationDestination(icon:Icon(Icons.map),label:'MAP')]);}
class Gsm extends StatelessWidget{const Gsm({super.key});@override Widget build(BuildContext c)=>const Valve(title:'GSM Valve Control',type:'GSM');}
class Lora extends StatelessWidget{const Lora({super.key});@override Widget build(BuildContext c)=>const Valve(title:'LoRa Valve Control',type:'LoRa');}
class Valve extends StatefulWidget{final String title,type;const Valve({super.key,required this.title,required this.type});@override State<Valve> createState()=>_ValveState();}
class _ValveState extends State<Valve>{double pos=0;bool bypass=false;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(widget.title)),body:SingleChildScrollView(padding:const EdgeInsets.all(10),child:Column(children:[Card(child:Padding(padding:const EdgeInsets.all(10),child:DropdownButtonFormField<String>(decoration:InputDecoration(labelText:'Valve ID (${widget.type})',border:const OutlineInputBorder()),items:[ '${widget.type}-001','${widget.type}-002'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(_){ }))),Card(child:Column(children:[const ListTile(title:Text('Valve Position',style:TextStyle(fontWeight:FontWeight.bold)),subtitle:Text('Requested / Actual')),Slider(value:pos,divisions:100,label:'${pos.round()}%',onChanged:(x)=>setState(()=>pos=x)),FilledButton(onPressed:(){},child:Text('SET VALVE TO ${pos.round()}%')),const SizedBox(height:8),Row(children:[Expanded(child:FilledButton(onPressed:(){},child:const Text('OPEN'))),const SizedBox(width:5),Expanded(child:FilledButton(onPressed:(){},child:const Text('CLOSE'))),const SizedBox(width:5),Expanded(child:FilledButton(onPressed:(){},child:const Text('STOP'))),const SizedBox(width:5),Expanded(child:FilledButton(onPressed:(){},child:const Text('E-STOP')))]),const SizedBox(height:10)])),Card(child:SwitchListTile(title:const Text('Low Voltage Bypass'),value:bypass,onChanged:(x)=>setState(()=>bypass=x))),Card(child:ListTile(title:const Text('Firmware / OTA'),trailing:FilledButton(onPressed:(){},child:const Text('OTA')))),Card(child:ListTile(title:const Text('OWNER REBIND'),onTap:(){}))]));}
class MapPage extends StatefulWidget{const MapPage({super.key});@override State<MapPage> createState()=>_MapState();}
class _MapState extends State<MapPage>{final MapController map=MapController();final List<Marker> markers=[Marker(point:const LatLng(12.9716,77.5946),width:44,height:44,child:const Icon(Icons.location_pin,size:44,color:Colors.red))];final List<String> valves=['GSM-001','GSM-002','LoRa-001'];void addValve(){setState(()=>valves.add('GSM-${(valves.length+1).toString().padLeft(3,'0')}'));} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('MAP'),actions:[IconButton(onPressed:addValve,icon:const Icon(Icons.add_location_alt))]),body:Column(children:[Padding(padding:const EdgeInsets.all(10),child:Row(children:[const Expanded(child:Text('Municipal Valve Map',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold))),FilledButton.icon(onPressed:addValve,icon:const Icon(Icons.add),label:const Text('ADD VALVE'))])),Expanded(child:FlutterMap(mapController:map,options:const MapOptions(initialCenter:LatLng(12.9716,77.5946),initialZoom:12),children:[TileLayer(urlTemplate:'https://tile.openstreetmap.org/{z}/{x}/{y}.png',userAgentPackageName:'com.municipal.operator'),MarkerLayer(markers:markers)])),const Padding(padding:EdgeInsets.all(10),child:Align(alignment:Alignment.centerLeft,child:Text('Valve List',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),),Expanded(child:ListView.builder(itemCount:valves.length,itemBuilder:(c,i)=>ListTile(leading:const Icon(Icons.location_pin,color:Colors.red),title:Text('Valve ID: ${valves[i]}'),subtitle:const Text('Latitude / Longitude'),trailing:IconButton(onPressed:(){},icon:const Icon(Icons.link)))))]));}
